# Generated by Django 4.0.5 on 2022-06-15 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='numero_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(max_length=1000)),
                ('profile_picture', models.ImageField(upload_to='images/')),
                ('phone_number', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(blank=True, max_length=200)),
                ('github_profile', models.URLField(blank=True)),
                ('twitter_profile', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='numero_Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=200, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=10000)),
                ('image_project', models.ImageField(upload_to='images/')),
                ('url', models.URLField()),
                ('project_files', models.URLField(blank=True)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='numeroapp.numero_profile')),
            ],
        ),
    ]
