# Generated by Django 4.0.5 on 2022-06-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numeroapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='numero_project',
            name='profile_name',
        ),
        migrations.AddField(
            model_name='numero_profile',
            name='profile_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
