# Generated by Django 4.0.5 on 2022-06-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numeroapp', '0002_remove_numero_project_profile_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='numero_profile',
            name='linked_profile',
            field=models.URLField(blank=True),
        ),
    ]
